name: ci
on: [pull_request, workflow_dispatch]
jobs:
  test-ci:
    name: test-ci
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          yarn install --frozen-lockfile
      - name: Check lerna version
        run: lerna --version
      - name: NPM bin lerna version
        run: $(npm bin)/lerna --version
      - name: Check lerna CLI version
        run: grep version node_modules/@lerna/cli/package.json

